version: '3.7'

services:
  back:
    build: ./back
    ports:
      - "3000:3000"
    volumes:
      - rails-bundle:/usr/local/bundle
      - ./back:/myapp

  front:
    build: ./front
    ports:
      - "8080:8080"
    volumes:
      - node_modules:/myapp/node_modules
      - ./front:/myapp
    environment:
      - WATCHPACK_POLLING=true
    tty: true
    stdin_open: true
    restart: always

  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - "8001:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8002:8080"
    volumes:
      - ./swagger/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
    depends_on:
      - swagger-api
    

  swagger-api:
    image: stoplight/prism:3
    ports:
      - "8003:4010"
    command: mock -h 0.0.0.0 /openapi.yaml
    volumes:
      - ./swagger/openapi.yaml:/openapi.yaml

volumes:
  rails-bundle:
    driver: local
  node_modules:
    driver: local
