version: "3.7"

services:
  back:
    build:
      context: ./back
    ports:
      - "3000:3000"
    volumes:
      - rails-bundle:/usr/local/bundle
      - ./back:/myapp
    depends_on:
      - db
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DB_USER: root
      DB_PW: password
      DB_HOST: db
      BUNDLE_PATH: /usr/local/bundle
      TZ: "Asia/Tokyo"
    tty: true
    stdin_open: true

  front:
    build: ./front
    ports:
      - "8080:8080"
    volumes:
      - ./front/app:/myapp/app
      - ./front/public:/myapp/public
      - ./front/.env.development.local:/myapp/.env.development.local
      - node_modules:/myapp/node_modules
    tty: true
    stdin_open: true

  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - "8001:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8002:8080"
    volumes:
      - ./swagger/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
    depends_on:
      - swagger-api

  swagger-api:
    image: stoplight/prism:3
    ports:
      - "8003:4010"
    command: mock -h 0.0.0.0 /openapi.yaml
    volumes:
      - ./swagger/openapi.yaml:/openapi.yaml

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      interval: 10s
      retries: 10
      start_period: 10s
    ports:
      - "3306:3306"

volumes:
  rails-bundle:
    driver: local
  node_modules:
    driver: local
