source "https://rubygems.org"

ruby "3.2.2"


gem "rails", "~> 7.0.6"
gem "mysql2", "~> 0.5"
gem "puma", ">= 5.0"
gem "bcrypt", "~> 3.1.12"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
gem 'devise', '~> 4.9', '>= 4.9.3'
gem "rack-cors"
gem 'devise_token_auth', '~> 1.2', '>= 1.2.2'
gem 'devise-i18n'
gem 'omniauth'
gem 'httpclient'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ]
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end
